const contractABI = [
  {
    "inputs":[
      {"internalType":"address","name":"_usdt","type":"address"},
      {"internalType":"address","name":"_kjc","type":"address"},
      {"internalType":"address","name":"_router","type":"address"},
      {"internalType":"address","name":"_distributor","type":"address"}
    ],
    "stateMutability":"nonpayable",
    "type":"constructor"
  },
  {
    "anonymous":false,
    "inputs":[
      {"indexed":false,"internalType":"address","name":"from","type":"address"},
      {"indexed":false,"internalType":"address","name":"referrer","type":"address"}
    ],
    "name":"ReferrerRegistered",
    "type":"event"
  },
  {
    "anonymous":false,
    "inputs":[
      {"indexed":false,"internalType":"address","name":"buyer","type":"address"},
      {"indexed":false,"internalType":"uint256","name":"usdtAmount","type":"uint256"},
      {"indexed":false,"internalType":"uint256","name":"kjcAmount","type":"uint256"}
    ],
    "name":"TokenPurchased",
    "type":"event"
  },
  {
    "inputs":[{"internalType":"address","name":"user","type":"address"}],
    "name":"referrerOf",
    "outputs":[{"internalType":"address","name":"","type":"address"}],
    "stateMutability":"view",
    "type":"function"
  },
  {
    "inputs":[{"internalType":"uint256","name":"usdtAmount","type":"uint256"}],
    "name":"buyWithReferral",
    "outputs":[],"stateMutability":"nonpayable",
    "type":"function"
  },
  {
    "inputs":[],
    "name":"getKJCperUSDT",
    "outputs":[{"internalType":"uint256","name":"","type":"uint256"}],
    "stateMutability":"view",
    "type":"function"
  },
  {
    "inputs":[{"internalType":"address","name":"referrer","type":"address"}],
    "name":"registerReferrer",
    "outputs":[],"stateMutability":"nonpayable",
    "type":"function"
  },
  {
    "inputs":[],"name":"owner",
    "outputs":[{"internalType":"address","name":"","type":"address"}],
    "stateMutability":"view",
    "type":"function"
  },
  {
    "inputs":[],"name":"distributor",
    "outputs":[{"internalType":"address","name":"","type":"address"}],
    "stateMutability":"view",
    "type":"function"
  }
];